apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-boot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: docker.io/mdottwo/terraform-hello-world:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer