apiVersion: v2
name: hello-world-chart
description: terraform-hello-world service Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - email: nweiser94@outlook.de
    name: Nico Weiser


apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: app
          image: docker.io/mdottwo/terraform-hello-world:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
