apiVersion: v2
name: hello-world-chart
description: terraform-hello-world service Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - email: nweiser94@outlook.de
    name: Nico Weiser


